export default {
  propertyDetails: {
    title: "",
    description: "",
    rooms: "",
    livingRooms: "",
    bathrooms: "",
    price: "",
    kitchens: "",
    area: "",
    floor: "",
    furnished: "",
    propertyStatus: "",
    status: "",
    governorate: "",
    city: "",
    neighborhood: "",
    coordinates: null,
    images: [],
    ownerProfile: null,
    createdAt: "",
    propertyContact: {
      name: "",
      email: "",
      phone: "",
      phone2: "",
      image: "",
    },
  },
  property: null,
  properties: [],
  error: "",
};
