export default {
  requestInfo: {
    area: "",
    bathrooms: "",
    city: "",
    coordinates: {},
    createdAt: "",
    location: "",
    description: "",
    floor: "",
    furnished: "",
    governorate: "",
    images: [],
    kitchens: "",
    livingRooms: "",
    neighborhood: "",
    ownerId: "",
    price: "",
    propertyContact: {
      email: "",
      name: "",
      phone: "",
      phone2: "",
    },
    room: "",
    status: "",
    title: "",
  },
  requests: [], // Add this line
  request: null,
  error: "",
};
